# docker-compose.yml

version: "3.9"  # Use the latest stable version
services:
  node:
    image: node:latest  # Use the latest Node.js image
    user: node
    working_dir: /app  # Use a standardized working directory
    environment:
      NODE_ENV: development  # Use environment variables for better configuration management
    volumes:
      - .:/app  # Use a standardized volume mount path
    ports:
      - "8080:8080"
    entrypoint: ["sh", "run.sh"]  # Use the entrypoint instruction for better readability
